### ISSUE TITLE
关于坐标系修改

### ISSUE THREAD

**Issue by whaqzhzd** [SergiusIW/collider#1]
您好，我观察代码中的世界，坐标系好像是x轴向左为正，y轴向下为负。如果我的世界是倒过来的，我需要修改什么吗？

My English is not good, the following is the result of Google translation, inaccurate, please forgive me。

Hello, I look at the world in the code. The coordinate system looks like the left side of the x-axis is positive, and the y-axis is down. If my world is upside down, do I need to change anything?

**Comment by SergiusIW** [comment]
Hi. I will assume you are referring to the 0.1.1 release of collider ( https://github.com/SergiusIW/collider/releases/tag/v0.1.1 ). You can use any convention for x-axis and y-axis. Your code does not need to change.

**Comment by whaqzhzd** [comment]
您好，我确实是使用的0.1.1版本。不过我不是直接使用的您的版本，由于我做的是HTML5游戏。所以我把您的项目改造成了TypeScript版本。

在绝大多数情况下使用良好。

在HBCircle或者HBRect里面有时候会因为getBoundEdgeComp这个方法而导致死循环。里面的实现当速度小于0的时候会用starttime。然后实体就不会发生移动了。stepToTime会导致实体一直循环碰撞分离碰撞分离。我陷入了一个困境。不知道下一步应该怎么做。

Hello, I really use the 0.1.1 version. But I'm not using your version directly because I'm doing HTML5 games. So I transformed your project into a TypeScript version.

Use well in most situations.

Sometimes inside HBCircle or HBRect will cause an infinite loop because of the getBoundEdgeComp method. The implementation inside will use starttime when the speed is less than zero. Then the entity will not move. stepToTime will cause the entity to have a cyclic collision to separate the collision separation. I got into a dilemma. Don't know what to do next.

I uploaded the remodeled [project.](https://github.com/whaqzhzd/collider-ts) If there is free time and interest, I don't know if it will help me. Thank you。

**Comment by whaqzhzd** [comment]
![image](https://user-images.githubusercontent.com/16913061/37951930-b8b55140-31d0-11e8-8c01-cb6d2361903d.png)

Hello, as shown in the picture. I know that collider should not cross under the right circumstances. Collider solves this problem well. I don't know where there is a problem with my modified version, which has led to this problem. It further led to an endless loop.

**Comment by whaqzhzd** [comment]
Thank you very much for your project. I have already found the problem. My problem is due to the problem that starRad and velRad are not initialized when HBCircle is constructed.
